name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare for libseccomp
      run: sudo apt-get install libseccomp-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: sudo /usr/share/rust/.cargo/bin/cargo test --verbose
